export const validation = {
  success: {},
  error: {
    number: "Number Required",
    avg_age_of_live_stocks: "Average age of live stocks Required",
    avg_age_of_trees: "Average age of tree Required",
    type_of_feed: "Type of feed Required",
    other_type_of_feed: "Other type of feed Required",
    number_hunted: 'Number Required',
    total_feed:"Total feed Required",
    self_produced: "Self Produced Required",
    purchased_from_market: "Purchased from market Required",
    steroids: "Steroids Required",
    meat: 'Meat Required',
    first_name: 'First Name Required',
    last_name: 'Last Name Required',
    village_name: 'Village Name Required',
    phone: 'Phone Required',
    family_name: 'Family Name Required',
    number_of_members: 'Number of family members is Required',
    number_of_trees: 'Number of Trees is required',
    member_name: 'Member name is required',
    member_gender: 'Member gender is required',
    member_age: 'Member age is required',
    social_security_number: 'Social Security Number Required',
    address: ' Address Required',
    total_land: 'Total land is required',
    cultivation: 'Cultivation is required',
    trees: 'Trees is required',
    trees_age: 'Trees age is required',
    poultry: 'Polutry is required',
    fishery: 'Fishery is rEquired',
    storage: 'Storage is required',
    area_allocated: 'Area allocated is required',
    output: 'Output is required',
    self_consumed: 'Self consumed is required',
    fed_to_livestock: 'Fed to livestock is required',
    sold_to_neighbours: 'Sold to neighbours is required',
    sold_for_industrial_use: 'Sold for industrial use is required',
    wastage: 'Wastage is required',
    other: 'Other is required',
    other_value: 'Other Value is requried',
    soil_health: 'Soil health is required',
    decreasing_rate: 'Decreasing rate is required',
    type_of_fertilizer_used: 'Type of fertilizer is required',
    type_of_pesticide_used: 'Type of pesticide is required',
    income_from_sale: 'Income from sale is required',
    yeild: 'Yeild is required',
    processing_method: "Processing Method Required",
    expenditure_on_inputs: 'Expenditure is required',
    month_planted: 'Month Planeted is required',
    month_harvested: 'Month harvested is required',
  },
};
