export const validation = {
  success: {},
  error: {
    land_measurement: 'Land measurement is Required',
    weight_measurement: 'Measurement is Required',
    number: 'Number is Required',
    avg_age_of_live_stocks: 'Average age of live stocks is Required',
    avg_age_of_trees: 'Average age of tree is Required',
    type_of_feed: 'Type of feed is Required',
    other_type_of_feed: 'Other type of feed is Required',
    number_hunted: 'Number is Required',
    total_feed: 'Total feed is Required',
    self_produced: 'Self Produced is Required',
    purchased_from_market: 'Purchased from market is Required',
    steroids: 'Steroids is Required',
    meat: 'Meat is Required',
    first_name: 'First Name is Required',
    last_name: 'Last Name is Required',
    village_name: 'Village Name is Required',
    phone: 'Phone is Required',
    family_name: 'Family Name is Required',
    number_of_members: 'Number of family members is Required',
    number_of_trees: 'Number of Trees is required',
    member_name: 'Member name is required',
    member_gender: 'Member gender is required',
    member_age: 'Member age is required',
    social_security_number: 'Social Security Number is Required',
    address: ' Address is Required',
    total_land: 'Total land is required',
    cultivation: 'Cultivation is required',
    trees: 'Trees is required',
    trees_age: 'Trees age is required',
    poultry: 'Polutry is required',
    fishery: 'Fishery is rEquired',
    storage: 'Storage is required',
    area_allocated: 'Area allocated is required',
    output: 'Output is required',
    self_consumed: 'Self consumed is required',
    fed_to_livestock: 'Fed to livestock is required',
    sold_to_neighbours: 'Sold to neighbours is required',
    sold_for_industrial_use: 'Sold for industrial use is required',
    wastage: 'Wastage is required',
    other: 'Other is required',
    other_value: 'Other Value is requried',
    soil_health: 'Soil health is required',
    decreasing_rate: 'Decreasing rate is required',
    type_of_fertilizer_used: 'Type of fertilizer is required',
    type_of_pesticide_used: 'Type of pesticide is required',
    income_from_sale: 'Income from sale is required',
    yeild: 'Yeild is required',
    processing_method: 'Processing Method Required',
    expenditure_on_inputs: 'Expenditure is required',
    month_planted: 'Month Planeted is required',
    month_harvested: 'Month harvested is required',
  },
};
